[package]
name = "baseline"
version = "0.1.0"
edition = "2021"

[dependencies]
raft-engine = { git = "https://github.com/TPC-TiKV/raft-engine.git", branch = "master" }
crossbeam-channel = "0.5.1"
raft = "0.6.0"
bytes = "1"